app/models/measurement.py
import os
import os.path as op

from app import db
from app.models.material import Material
from app.models.experiment import Experiment
from app.config import BASE_DIR
from sqlalchemy import event

tags = db.Table(
    'tags',
    db.Column('experiment_id', db.Integer, db.ForeignKey('experiment.id'), primary_key=True),
    db.Column('measurement_id', db.Integer, db.ForeignKey('measurement.id'), primary_key=True)
)


class Base(db.Model):

    __abstract__  = True

    id           = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(),
                              onupdate=db.func.current_timestamp())

    authors      = db.Column(db.String(120))
    parameters   = db.Column(db.Text)
    description  = db.Column(db.Text)
    date_measure = db.Column(db.Date)

    filename     = db.Column(db.Unicode(128))


class Measurement(Base):
    # , passive_deletes = 'all', nullable=False
    material_id = db.Column(db.Integer, db.ForeignKey('material.id'))
    material = db.relationship(Material, backref=db.backref('measurements', lazy='dynamic'), order_by=Material.name)

    # category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    # category = db.relationship(Category, backref=db.backref('measurements', lazy='dynamic'))

    experiments = db.relationship(Experiment, secondary=tags, lazy='subquery', backref=db.backref('experiment', lazy=True))

    def __str__(self):
        return self.material if self.material else ''


    def __repr__(self):
        return '<Measurement {} ({})>'.format(self.material, self.parameters)


# Delete hooks for models, delete files if models are getting deleted
@event.listens_for(Measurement, 'after_delete')
def del_file(mapper, connection, target):
    if target.filename:
        try:
            os.remove(op.join(BASE_DIR, 'files', target.filename))
        except OSError:
            # Don't care if was not deleted because it does not exist
            pass














#     @staticmethod
#     def generate_slug(target, value, oldvalue, initiator):
#         if value and (not target.slug or value != oldvalue):
#             target.slug = slugify(value)
#
#
# # https://www.michaelcho.me/article/using-model-callbacks-in-sqlalchemy-to-generate-slugs
# event.listen(Experiment.name, 'set', Experiment.generate_slug, retval=False)

# https://www.michaelcho.me/article/using-model-callbacks-in-sqlalchemy-to-generate-slugs

# class SpectralData(Base):
#
#     material_id = db.Column(db.Integer, db.ForeignKey('material.id'))
#     material = db.relationship(Material, backref=db.backref('spectraldata', lazy='dynamic'))
#
#
# class AngularData(Base):
#
#     material_id = db.Column(db.Integer, db.ForeignKey('material.id'))
#     material = db.relationship(Material, backref=db.backref('angulardata', lazy='dynamic'))
#


    # description  = db.Column(db.Text)
    # datetime.datetime.strptime('21/02/2016', '%d/%m/%Y').date()

    # def __init__(self, material, authors, excerpt, date_measure, filename):
    #
    #     self.material     = material            # name of material
    #     self.authors      = authors             # authors
    #     self.date_measure = date_measure        # date of measurement
    #     self.excerpt      = excerpt             # parameters, short description
    #     self.filename     = filename            # relative path and filename

    # @property
    # def haha(self):
    #     return 'haha'
    #
    # def hello(self):
    #     pass



    # @staticmethod
    # def define_tags(target, value, oldvalue, initiator):
    #     from scipy.io import loadmat
    #     print(loadmat('files/'+value))
    #     pass

# event.listen(Measurement.filename, 'set', Measurement.define_tags, retval=False)

app/views/measurements.py
import os.path as op

from flask import Blueprint, render_template, Markup, current_app, request
from app.models.measurement import Measurement
from app.models.material import Material
from app.models.experiment import Experiment
from app.config import BASE_DIR

import numpy as np
from scipy.io import loadmat

# https://plot.ly/python/reference/
# import plotly.offline as py
import app.utils.plotly_override as py
import plotly.graph_objs as go


measurements = Blueprint('measurements', __name__, url_prefix='/measurement')

#
# @measurements.route('/')
# def measurement():
#     materials = Material.query.all()
#
#     return render_template(
#         'measurements/measurements.html',
#         materials=materials)





@measurements.route('/<int:measurement_id>')
def show_measurement(measurement_id):
    # show the post with the given id, the id is an integer

    measurement_data = Measurement.query.get_or_404(measurement_id)

    experiments = {
        'angular': Experiment.query.get(1),
        'spectral': Experiment.query.get(2),
    }


    plot_div = dict()


    # file_path = op.join(BASE_DIR, 'files', measurement.filename)
    file_path = op.join(current_app.root_path, 'files', measurement_data.filename)

    if op.isfile(file_path):

        data = loadmat(file_path, squeeze_me=True, struct_as_record=True)

        if experiments['spectral'] in measurement_data.experiments \
                and data.keys() & {'spectral_lambda', 'spectral_I'}:

            sl = data['spectral_lambda']
            si = data['spectral_I']

            plot_div['spectral'] = generate_spectral_plot(sl, si)

        if experiments['angular'] in measurement_data.experiments \
                and data.keys() & {'angular_x', 'angular_y', 'angular_I'}:

            plot_div['angular'] = generate_angular_plot(data['angular_x'], data['angular_y'], data['angular_I'])
            # plot_div['surf'] = generate_angular_surface(x, y, I)


    return render_template('measurements/measurement.html',
                           # spectral_data=spectral_data,
                           # spectral_layout=spectral_layout,
                           measurement=measurement_data,
                           # description=Markup(data['desc']),
                           div_placeholder=plot_div
                           )


@measurements.route('/test/plot.png')
def plot_test():
    from flask import make_response

    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
    from matplotlib.figure import Figure
    import random
    from io import BytesIO

    fig = Figure()
    axis = fig.add_subplot(1, 1, 1)

    xs = range(100)
    ys = [random.randint(1, 50) for x in xs]

    axis.plot(xs, ys)
    canvas = FigureCanvas(fig)
    output = BytesIO()
    # output = StringIO()  # python 2.7x
    canvas.print_png(output)
    response = make_response(output.getvalue())
    response.mimetype = 'image/png'
    return response


def generate_plot():
    import json
    import plotly

    import pandas as pd
    import numpy as np

    rng = pd.date_range('1/1/2011', periods=7500, freq='H')
    ts = pd.Series(np.random.randn(len(rng)), index=rng)

    graphs = [
        dict(
            data=[
                dict(
                    x=[1, 2, 3],
                    y=[10, 20, 30],
                    type='scatter'
                ),
            ],
            layout=dict(
                title='first graph'
            )
        ),

        dict(
            data=[
                dict(
                    x=[1, 3, 5],
                    y=[10, 50, 30],
                    type='bar'
                ),
            ],
            layout=dict(
                title='second graph'
            )
        ),

        dict(
            data=[
                dict(
                    x=ts.index,  # Can use the pandas data structures directly
                    y=ts
                )
            ]
        )
    ]

    # Add "ids" to each of the graphs to pass up to the client
    # for templating
    ids = ['graph-{}'.format(i) for i, _ in enumerate(graphs)]

    # Convert the figures to JSON
    # PlotlyJSONEncoder appropriately converts pandas, datetime, etc
    # objects to their JSON equivalents
    graphJSON = json.dumps(graphs, cls=plotly.utils.PlotlyJSONEncoder)

    return ids, graphJSON

#
# def generate_spectral_plot(wavelength, intensity):
#     import json
#     import plotly
#
#     import numpy as np
#
#     data = dict(
#         x=np.asarray(wavelength),
#         y=intensity
#     )
#
#     layout = dict(
#         title='first graph'
#     )
#
#     # Convert the figures to JSON
#     # PlotlyJSONEncoder appropriately converts pandas, datetime, etc
#     # objects to their JSON equivalents
#     return json.dumps(data, cls=plotly.utils.PlotlyJSONEncoder), json.dumps(layout, cls=plotly.utils.PlotlyJSONEncoder)


def generate_spectral_plot(wavelength, intensity):

    # plot(figure_or_data, show_link=True, link_text='Export to plot.ly', validate=True, output_type='file',
    #      include_plotlyjs=True, filename='temp-plot.html', auto_open=True, image=None, image_filename='plot_image',
    #      image_width=800, image_height=600)

    data = [
        go.Scatter(
            x=wavelength,
            y=intensity,
        )
    ]

    layout = go.Layout(
        title='',
        xaxis=dict(
            title='Wavelength (nm)',
            ticks='inside',
            showline=True,
        ),
        yaxis=dict(
            title="Intensity",
            showexponent='all',
            exponentformat='none',
            separatethousands=True,
            ticks='inside',
            showline=True,
        ),
        margin=dict(
            l=80,
            r=20,
            t=30,
            b=80,
            pad=10,
            autoexpand=True,
        ),
    )

    fig = go.Figure(data=data, layout=layout)

    mode_bar_buttons_to_remove = ['sendDataToCloud', 'zoomIn2d', 'zoomOut2d', 'resetScale2d', 'hoverClosestCartesian',
                                  'hoverCompareCartesian']

    # toggleSpikelines
    plot_div = py.plot(
        fig,
        output_type='div',
        include_plotlyjs=False,
        modeBarButtonsToRemove=mode_bar_buttons_to_remove
    )

    return plot_div



def generate_angular_plot(x, y, intensity):

    # plot(figure_or_data, show_link=True, link_text='Export to plot.ly', validate=True, output_type='file',
    #      include_plotlyjs=True, filename='temp-plot.html', auto_open=True, image=None, image_filename='plot_image',
    #      image_width=800, image_height=600)

    data = [
        go.Heatmap(
            x=x,
            y=y,
            z=intensity,
            type='heatmap',
            zsmooth='best',
            colorscale='Viridis',
            hoverinfo='z',
            transpose=True,
            colorbar=dict(
                title='Intensity',
                titleside='top',
                lenmode='fraction',
                len=0.8,
                showexponent='all',
                exponentformat='none',
                separatethousands=True,
                xanchor='left',
                xpad=20,
                x=1.0,
                yanchor='middle',
                ypad=10,
                y=0.5,
                ticks='inside',
            ),
        ),
        # go.Surface(
        #     x=x,
        #     y=y,
        #     z=intensity,
        # )
    ]

    phi_axis_ticks = [0, 60, 120, 180, 240, 300]
    theta_axis_ticks = [0, 30, 60, 90]

    axis_labels, axis_lines = [], []
    for tick in phi_axis_ticks:

        label = dict(
            visible=True,
            clicktoshow=False,
            opacity='1',
            # bgcolor='rgba(0, 0, 0, 0)',
            # bordercolor='rgba(0, 0, 0, 0)',
            # borderpad='1',
            # borderwidth='1',
            text='{}º'.format(tick),
            textangle=tick if tick < 90 or tick > 270 else 180+tick,
            align='center',
            xref='x',
            xanchor='center',
            x=1.7 * np.sin(tick * np.pi / 180.),
            ax=30 * np.sin(tick * np.pi / 180.),
            xshift='0',
            yref='y',
            yanchor='middle',
            y=1.7 * np.cos(tick * np.pi / 180.),
            ay=-30 * np.cos(tick * np.pi / 180.),
            yshift='0',
            showarrow=True,
            arrowhead=0,
            arrowsize=1,
            arrowwidth=1,
        )
        axis_labels.append(label)

        line = dict(
            visible=True,
            layer='above',
            fillcolor='rgba(0, 0, 0, 0)',
            line=dict(
                color='rgb(125, 125, 125)',
                width=1,
                dash='dot'
            ),
            type='line',
            xref='x',
            x0=0,
            x1=1.7 * np.sin(tick * np.pi / 180.),
            yref='y',
            y0=0,
            y1=1.7 * np.cos(tick * np.pi / 180.),
        )
        axis_lines.append(line)



    for tick in theta_axis_ticks:

        label = dict(
            visible=True,
            clicktoshow=False,
            opacity='1',
            bgcolor='rgba(256, 256, 256, 0.5)',
            # bordercolor='rgba(0, 0, 0, 0)',
            # borderpad='1',
            borderwidth='0',
            text='{}º'.format(tick),
            textangle=0,
            align='center',
            font=dict(
                color='rgba(176, 176, 176)',
            ),
            xref='x',
            xanchor='center',
            x=0,
            ax=30,
            xshift='0',
            yref='y',
            yanchor='middle',
            y=tick * np.pi / 180.,
            ay=0,
            yshift='0',
            showarrow=True,
            arrowhead=0,
            arrowsize=1,
            arrowwidth=1,
            arrowcolor='rgb(176, 176, 176)',
        )
        axis_labels.append(label)

        if tick != 0 or tick != 90:
            line = dict(
                visible=True,

app/templates/measurements/measurement.html
{# This simple template derives from ``base.html``. See ``base.html`` for
   more information about template inheritance. #}
{%- extends "base.html" %}

{# Loads some of the macros included with Flask-Bootstrap. We are using the
   utils module here to automatically render Flask's flashed messages in a
   bootstrap friendly manner #}
{% import "bootstrap/utils.html" as utils %}


{# Inside the ``content`` is where you should place most of your own stuff.
   This will keep scripts at the page end and a navbar you add on later
   intact. #}
{% block content %}
    {%- with messages = get_flashed_messages(with_categories=True) %}
        {%- if messages %}
            <div class="row">
                <div class="col-md-12">
                    {{ utils.flashed_messages(messages) }}
                </div>
            </div>
        {%- endif %}
    {%- endwith %}
{#    <ol class="breadcrumb">#}
{#      <li><a href="#">Home</a></li>#}
{#      <li><a href="#">Library</a></li>#}
{#      <li class="active">Data</li>#}
{#    </ol>#}
    <div class="jumbotron text-center">
      <h1>{{measurement.material}}</h1>
      <p>Author(s): {{measurement.authors}}, Date of measure: {{measurement.date_measure.strftime('%Y-%m-%d')}}</p>
    </div>
    <div class="container">

{#        <div class="row">#}
{#          <div class="col-sm-8 col-sm-offset-1">#}
{#            <h1>{{measurement.material}}</h1>#}
{#            <p>Author(s): {{measurement.authors}}, Date of measure: {{measurement.date_measure.strftime('%d/%m/%Y')}}</p>#}
{#          </div>#}
{#        </div>#}

        <div class="row">
          <div class="col-sm-8 col-sm-offset-1">
            <h2>Parameters</h2>
          </div>
          <div class="col-sm-2">
            <!-- Split button -->
            <h2>
            <div class="btn-group">
              <a class="btn btn-primary" href="/api/download/matlab/{{  measurement.id }}" target="_blank"><i class="glyphicon glyphicon-download-alt"></i> Download</a>
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="/api/download/matlab/{{  measurement.id }}">Matlab format</a></li>
                <li><a href="/api/download/json/{{  measurement.id }}">Json format</a></li>
              </ul>
            </div>
            </h2>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            {{measurement.parameters | markdown | indent(8, false) | safe}}

            <h2>Description</h2>

            {{ measurement.description | markdown | indent(8, false) | safe}}

            {%- if div_placeholder['spectral'] %}
            <h2>Spectral data</h2>
            {{ div_placeholder['spectral'] | safe }}
            {%- endif %}

            {%- if div_placeholder['angular'] %}
            <h2>Angular data</h2>

            {{ div_placeholder['angular'] | safe }}
            {%- endif %}

{#            {%- if div_placeholder['surf'] %}#}
{#            {{ div_placeholder['surf'] | safe }}#}
{#            {%- endif %}#}

          </div>
      </div>
    </div>
{%- endblock %}

{% block head %}
    {{super()}}

    <!-- Plotly.js -->
{#   <script src="https://cdn.plot.ly/plotly-1.2.0.min.js"></script>#}
   <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

{%- endblock head %}



{#{% block scripts %}#}
{#    {{super()}}#}
{##}
{#    <!-- D3.js -->#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>#}
{#    <!-- jQuery -->#}
{#    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>#}
{#    <!-- Plotly.js -->#}
{#    <script src="https://d14fo0winaifog.cloudfront.net/plotly-basic.js"></script>#}
{##}
{#    <script type="text/javascript">#}
{##}
{#        var spectral_data = { {spectral_data}};#}
{#        var spectral_layout = {{spectral_layout | safe}};#}
{##}
{##}
{#        Plotly.newPlot('spectral-graph', spectral_data);#}
{##}
{#        var trace1 = {#}
{#          x: [1, 2, 3, 4],#}
{#          y: [10, 15, 13, 17],#}
{#          type: 'scatter'#}
{#        };#}
{#        var trace2 = {#}
{#          x: [1, 2, 3, 4],#}
{#          y: [16, 5, 11, 9],#}
{#          type: 'scatter'#}
{#        };#}
{#        var data = [trace1, trace2];#}
{#        Plotly.newPlot('angular-graph', spectral_data);#}
{##}
{#    </script>#}
{##}
{#{%- endblock scripts %}#}
{##}




{##}
{#                <!-- Split button -->#}
{#                <div class="btn-group">#}
{#                  <button type="button" class="btn btn-primary">Action</button>#}
{#                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                    <span class="caret"></span>#}
{#                    <span class="sr-only">Toggle Dropdown</span>#}
{#                  </button>#}
{#                  <ul class="dropdown-menu">#}
{#                    <li><a href="#">Action</a></li>#}
{#                    <li><a href="#">Another action</a></li>#}
{#                    <li><a href="#">Something else here</a></li>#}
{#                    <li role="separator" class="divider"></li>#}
{#                    <li><a href="#">Separated link</a></li>#}
{#                  </ul>#}
{#                </div>#}
{##}

app/templates/measurements/measurements.html
{# This simple template derives from ``base.html``. See ``base.html`` for
   more information about template inheritance. #}
{%- extends "base.html" %}

{# Loads some of the macros included with Flask-Bootstrap. We are using the
   utils module here to automatically render Flask's flashed messages in a
   bootstrap friendly manner #}
{% import "bootstrap/utils.html" as utils %}


{# Inside the ``content`` is where you should place most of your own stuff.
   This will keep scripts at the page end and a navbar you add on later
   intact. #}
{% block content %}
        {%- with messages = get_flashed_messages(with_categories=True) %}
            {%- if messages %}
                <div class="row">
                    <div class="col-md-12">
                        {{ utils.flashed_messages(messages) }}
                    </div>
                </div>
            {%- endif %}
        {%- endwith %}
    <div class="container">

        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">

                <h1>About the measurement</h1>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's
                    standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
                    make a type specimen book. It has survived not only five centuries, but also the leap into electronic
                    typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset
                    sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
                    PageMaker including versions of Lorem Ipsum.
                </p>

                {% for material in materials %}
                    <h3>{{material.name}}</h3>

                    <table class="table" id="experiments">
                      <thead>
                        <tr>
{#                          <th>Material</th>#}
                          <th>Parameters</th>
                          <th>Experiment</th>
{#                          <th>Date</th>#}
                        </tr>
                      </thead>
                      <tbody>

                    {% for measurement in material.measurements.all() %}
                        <tr>
{#                          <th scope="row"><a href="{{ url_for('measurements.show_measurement', measurement_id=measurement.id) }}">{{ measurement.material }}</a></th>#}
                            <th scope="row"><a href="{{ url_for('measurements.show_measurement', measurement_id=measurement.id) }}">{{ measurement.parameters }}</a></th>
                            <td width="10%">{{ measurement.experiments|join(', ') }}</td>
{#                          <td>{{ measurement.date_measure }}</td>#}
                        </tr>
                    {% endfor %}
                      </tbody>
                    </table>

                {% endfor %}

            </div>
        </div>
    </div>
{%- endblock %}

{% block scripts %}
    {{super()}}
{%- endblock scripts %}